name: commit
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Format
        run: zig fmt --check *.zig src/
      
      - name: Test OpenSSL
        run: zig build test -DUSE_OPENSSL -DUSE_QUIC
      
      - name: Test WolfSSL
        run: zig build test -DUSE_WOLFSSL -DUSE_QUIC

      - name: Test BoringSSL
        run: zig build test -DUSE_BORINGSSL -DUSE_QUIC
        
